project_id = "roeordbqholjedzrhyvw"

[functions.check-behind-schedule]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.get-invite-by-token]
verify_jwt = false
