project_id = "roeordbqholjedzrhyvw"

[functions.check-behind-schedule]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.get-invite-by-token]
verify_jwt = false

[functions.migrate-sales-template]
verify_jwt = false

[functions.builder-chat]
verify_jwt = false

[functions.process-builder-upload]
verify_jwt = false
